### ISSUE TITLE
How do the SQLite database files work?

### ISSUE THREAD

**Issue by astonm** [expo/expo-docs#63] opened 2017-05-15 01:50 UTC
I'm not yet sure if this is a missing piece in the document, or just a limitation of Expo's SQLite implementation, but my guess is the former, so I'm filing an issue here.

I had an existing SQLite .db file I wanted to ship statically with my app, but I couldn't figure out how to get it into the app in the first place. Based on the documentation, I supposed the `Asset` handling stuff might help, but that seemed not to work at all. Eventually I gave up, created a new database file, and searched various directories to find where that file landed. Dropping my existing database file in the same directory made it possible for me to see it from my Expo code.

Is dropping files into that location going to do the right thing once I try to deploy widely? If so, it would be awesome to update the documentation to explain where the files land so that they can be manipulated however by the developer. If this hack isn't going to do the right thing later, instead I think the documentation should warn developers not to do it. And hopefully also it would share the right way to accomplish the same goal.

Happy to take a shot at submitting a PR to update the docs if you guys can let me know which way is the right way.

**Comment by nikki93** [comment] 2017-05-17 22:29
Hey @astonm 

I haven't tried this use-case yet (using a pre-exitent db). One way to do this is to download from a remote URI / Asset as you suggested and then move it to the correct location in the FS. The code at https://github.com/expo/expo-sdk/blob/master/src/Asset.js#L118-L126 downloads from a remote URI to a local file. If you use `cache: false` and use a local path of `/SQLite/blah.db` then opening `blah.db` in the SQLite module will work.

I plan to improve this FS API to be more user-facing and fully featured soon. For now this ^ should work, I have yet to try it properly. The SQLite and FS stuff is still in its early stages. Jump on our slack at slack.expo.io and ping me ('nikki' on there) to discuss!

**Comment by nikki93** [comment] 2017-06-02 23:12
@astonm based on our Slack convo it seems you got this working. https://github.com/expo/expo/issues/108 will allow a proper solution here going ahead, but don't have time to work on that till SDK 19 or later. In light of that, gonna close this issue. Feel free to post the solution you came up with somewhere so people can refer to it!

**Closed by nikki93** 2017-06-02 23:12 UTC
Labels: enhancement

**Comment by astonm** [comment] 2017-06-03 02:25
In case anyone is looking to do something similar, the gist of what I did is below. Section 1 is a function that tweaks the existing `Asset.downloadAsync` to allow saving to a specific path, Section 2 is how to create and download the database asset, and the last line shows how to open the database using the expo `SQLite` library.

```javascript
import { Asset, SQLite } from 'expo';

Asset.prototype.downloadAsyncTo = async function(path) {
  if (this.downloaded) {
    return;
  }
  if (this.downloading) {
    await new Promise((resolve, reject) =>
      this.downloadCallbacks.push({ resolve, reject })
    );
    return;
  }
  this.downloading = true;

  try {
    let exists, md5, uri;
    ({
      exists,
      md5,
      uri,
    } = await NativeModules.ExponentFileSystem.getInfoAsync(path, {
      // cache: true,
      md5: true,
    }));
    if (!exists || md5 !== this.hash) {
      ({
        md5,
        uri,
      } = await NativeModules.ExponentFileSystem.downloadAsync(
        this.uri,
        path,
        {
          md5: true,
        }
      ));
      if (md5 !== this.hash) {
        throw new Error(
          `Downloaded file for asset '${this.name}.${this.type}' ` +
            `failed MD5 integrity check`
        );
      }
    }
    this.localUri = uri;
    this.downloaded = true;
    this.downloadCallbacks.forEach(({ resolve }) => resolve());
  } catch (e) {
    this.downloadCallbacks.forEach(({ reject }) => reject(e));
    throw e;
  } finally {
    this.downloading = false;
    this.downloadCallbacks = [];
  }
}


/***********************************************/
dbAsset = new Asset({
  'name': 'my_database',
  'type': 'db',
  'hash': '70c1c7e28cb655995950a34c7ccd71b8', // calculate md5 hash here
  'uri': 'http://domain.com/my_database_path.db', // path to the file somewhere on the internet
});
dbAsset.downloadAsyncTo('SQLite/etymonline.db')
/***********************************************/

db = SQLite.openDatabase('my_database.db');
```

**Comment by nikki93** [comment] 2017-06-08 05:21
@astonm just to check -- in the last 3 lines the `etymonline.db` and `my_database.db` mentions should be the same name `x.db` is that correct?

**Comment by outaTiME** [comment] 2017-06-30 15:26
Hi @nikki93, im trying to use the above solution but if i use path with folder like `SQLite/my_database.db` or `/SQLite/blah.db` with cache in `false` the file is not created ... but if i remove the folder it works, something related with the `downloadAsync` method? 

Thanks !!!

**Comment by florentroques** [comment] 2017-06-30 18:44
@outaTiME the downloadAsync method doesn't create a directory if you specify a path with a folder for now as of SDK 18 ([downloadAsync's iOS code] (https://github.com/expo/expo/blob/ios/sdk18/ios/Exponent/Versioned/Modules/Api/EXFileSystem.m#L43-L48)) and we do not have any directory creation method available for now.

But I saw they're implementing new FileSystem methods nowadays ([future makeDirectoryAsync method](https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Modules/Api/EXFileSystem.m#L266-L291)).

I guess we'll have these new FileSystem methods for SDK 19!

**Comment by outaTiME** [comment] 2017-06-30 23:33
@florentroques yup I'm expecting the new 19 SDK, but the solution (or workaround) of @nikki93 doesn't work on first execution because the `downloadAsync` method does not create `SQLite` folder, therefore it does not take the downloaded file and creates an new in `SQLite` folder, take a look:

<img width="793" alt="screen shot 2017-06-30 at 8 27 17 pm" src="https://user-images.githubusercontent.com/140472/27756956-8671605c-5dd2-11e7-9fed-24b6ec7d6564.png">

How can handle this?

**Comment by florentroques** [comment] 2017-07-01 14:26
@outaTiME I found the issue. Actually, the SQLite folder needs to be created at first for the downloadAsync method to be able to save a file to the SQLite folder.

1. create a dummy DB to create the SQLite folder
<img width="604" alt="screen shot 2017-07-01 at 16 01 06" src="https://user-images.githubusercontent.com/1901827/27762737-f7ae1e40-5e77-11e7-9f72-6928cb4947a8.png">

2. download the desired SQLite file
<img width="606" alt="screen shot 2017-07-01 at 16 10 52" src="https://user-images.githubusercontent.com/1901827/27762740-0291168c-5e78-11e7-87b4-15f01ead3e81.png">

Here's the workaround to create the SQLite folder by creating a dummy SQLite db:
```javascript
//creates a dummy SQLite DB to create the SQLite folder
async makeSQLiteDirAsync() {
  const dbTest = SQLite.openDatabase('dummy.db');

  try {
    await dbTest.transaction(tx => tx.executeSql(''));
  } catch(e) {
      console.log('error while executing SQL in dummy DB');
      console.log(e.message);
  }
}
```

Then you call this function before using the [downloadAsyncTo](https://github.com/expo/expo-docs/issues/63#issuecomment-305944573) method  to make sure the folder is created before the first download
```javascript
await this.makeSQLiteDirAsync();
await dbAsset.downloadAsyncTo(`SQLite/${dbAssetFullName}`);
const db = SQLite.openDatabase(dbAssetFullName);
```
I created an example repo for this [https://github.com/florentroques/expo-remote-sqlite-download](https://github.com/florentroques/expo-remote-sqlite-download)

**Comment by outaTiME** [comment] 2017-07-04 03:25
Thanks for your time @florentroques awesome the example repo you made ... it works perfectly, basically the problem is the creation of the folder `SQLite`, ideally `SQLite.openDatabase` should allow any path and not be limited to the `SQLite` folder only. 

I assume this will be solved when filesystem support released (https://github.com/expo/expo/issues/108), right?

Thanks again

**Comment by outaTiME** [comment] 2017-07-04 04:10
BTW, im running with another problem the `downloadAsyncTo` method does not intercept a 404 from remote when downloading. 

I create issue in expo for this problem https://github.com/expo/expo/issues/326

**Comment by florentroques** [comment] 2017-07-10 12:21
Regarding `SQLite.openDatabase`, after asking @nikki on slack, his answer is "only SQLite folder scope".
Will update my answer when I get more news.

**Comment by j2l** [comment] 2017-07-22 13:39
You just solved ony of my main problems!
Thanks!

**Comment by NunoCardoso** [comment] 2017-10-11 10:06
I have a problem, I download a DB, and in iOS, I put it on Expo.FileSystem.documentDirectory.replace("file://", "") + 'SQLite'.

I see it on ~/Library/Developer/CoreSimulator/Devices/E1641A61-8A3A-407B-9B1A-61EA5BAE47EC/data/Containers/Data/Application/5EC8AD6E-2382-4ABF-BC30-541867521539/Documents/ExponentExperienceData/%2540nuno%252F{appname}/SQLite

but when I load the app, it creates a blank one on  %40nuno%2F{appname}/SQLite instead of %2540nuno%252F{appname}/SQLite.

Why is that? Why is SQLite.openDatabase(name) trying to open the DB in a different directory that given by Expo.FileSystem.documentDirectory + "/SQLite" ?

**Comment by gaving** [comment] 2017-10-29 17:34
Can anyone confirm if this works on the latest SDK (i.e. 22) for them?

Having issues here:- https://gist.github.com/gaving/a2b54a96192624e3801dc8db5bd5e00f

Basically just getting a "Error code 10: disk I/O error" even though it's opening the file.. started delving into the websql package + WebSQLTransaction.js file before quickly glazing over. 😱

**Comment by rodrigore** [comment] 2018-03-14 02:57
@gaving  I also have this error in SDK 25. 

Did you solve the problem?

**Comment by gaving** [comment] 2018-03-14 10:16
@rodrigore Sad to say I didn't, cost me hours before I eventually gave up! 😢

**Comment by baochungit** [comment] 2018-09-30 17:30
@nikki93 Could you tell me where to set `cache: false` ? It seems that the result of `txn.executeSql` is cached, the db file is updated but somehow I always get the old result.
